'use client';

import React, { useState } from 'react';
import jsPDF from 'jspdf';
import { AppShell } from '@/components/layout/AppShell';
import { useSaaS } from '@/context/SaaSContext';
import { StatCard } from '@/components/ui/StatCard';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Select } from '@/components/ui/Select';
import { Modal } from '@/components/ui/Modal';
import { useToast } from '@/components/ui/Toast';
import {
  BarChart3,
  TrendingUp,
  Download,
  Filter,
  Calendar,
  Building2,
  Package,
  Users,
  CreditCard,
  Sparkles,
  Receipt,
  ArrowRight
} from '@/components/icons';
import { mockProducts } from '@/data/mockData';

export default function AnalyticsPage() {
  const { currentBusiness, branches } = useSaaS();
  const { addToast } = useToast();

  const [selectedRange, setSelectedRange] = useState<'30d' | '90d' | 'ytd'>('30d');
  const [selectedBranchFilter, setSelectedBranchFilter] = useState('all');

  // Export Modal state
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [exportFormat, setExportFormat] = useState('PDF');
  const [exportRange, setExportRange] = useState('30d');

  const branchSalesData = [
    { name: 'Colon Free Zone Hub', amount: 132000, percent: 39 },
    { name: 'Calle 50 Flagship', amount: 94500, percent: 28 },
    { name: 'Multiplaza Mall Branch', amount: 68200, percent: 20 },
    { name: 'David Chiriqui Express', amount: 41800, percent: 13 }
  ];

  const handleExecuteExport = () => {
    setIsExportModalOpen(false);

    const reportName = `BI_Executive_Report_${exportRange}_${Date.now()}`;

    if (exportFormat === 'PDF') {
      try {
        const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        
        // Header
        doc.setFillColor(30, 41, 59);
        doc.rect(0, 0, 210, 28, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(16);
        doc.text('BUSINESS INTELLIGENCE & ANALYTICS REPORT', 15, 12);
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Consolidated Multi-Branch Executive Summary - ${currentBusiness.name}`, 15, 20);
        doc.text(`Range: ${exportRange.toUpperCase()}`, 195, 16, { align: 'right' });

        // Executive KPIs
        let y = 40;
        doc.setFillColor(248, 250, 252);
        doc.setDrawColor(226, 232, 240);
        doc.roundedRect(15, y, 88, 26, 2, 2, 'FD');
        doc.setTextColor(30, 41, 59);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text('CONSOLIDATED GROSS SALES', 19, y + 7);
        doc.setFontSize(14);
        doc.setTextColor(37, 99, 235);
        doc.text('$340,350.00', 19, y + 17);

        doc.roundedRect(107, y, 88, 26, 2, 2, 'FD');
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(10);
        doc.text('NET PROFIT MARGIN', 111, y + 7);
        doc.setFontSize(14);
        doc.setTextColor(5, 150, 105);
        doc.text('31.8%', 111, y + 17);

        y = 72;
        doc.roundedRect(15, y, 88, 26, 2, 2, 'FD');
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(10);
        doc.text('PANAMA ITBMS (7%) TAX', 19, y + 7);
        doc.setFontSize(14);
        doc.setTextColor(124, 58, 237);
        doc.text('$23,824.50', 19, y + 17);

        doc.roundedRect(107, y, 88, 26, 2, 2, 'FD');
        doc.setTextColor(30, 41, 59);
        doc.setFontSize(10);
        doc.text('INVENTORY TURNOVER', 111, y + 7);
        doc.setFontSize(14);
        doc.setTextColor(217, 119, 6);
        doc.text('4.6x Velocity', 111, y + 17);

        // Branch Breakdown Table
        y = 110;
        doc.setFillColor(241, 245, 249);
        doc.rect(15, y, 180, 8, 'F');
        doc.setTextColor(51, 65, 85);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(9);
        doc.text('Branch Name', 19, y + 5.5);
        doc.text('Volume Share', 110, y + 5.5);
        doc.text('Gross Revenue ($)', 185, y + 5.5, { align: 'right' });

        branchSalesData.forEach((b) => {
          y += 10;
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(30, 41, 59);
          doc.text(b.name, 19, y);
          doc.text(`${b.percent}%`, 110, y);
          doc.setFont('helvetica', 'bold');
          doc.text(`$${b.amount.toLocaleString()}.00`, 185, y, { align: 'right' });
        });

        // Footer
        y = 265;
        doc.setDrawColor(203, 213, 225);
        doc.line(15, y, 195, y);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(100, 116, 139);
        doc.text(`Generated by NEXUS SaaS BI Intelligence Engine for ${currentBusiness.name}`, 105, y + 8, { align: 'center' });

        doc.save(`${reportName}.pdf`);
        addToast(`BI Executive Report generated & downloaded (${reportName}.pdf)`, 'success');
      } catch (err) {
        console.error('PDF export error:', err);
      }
    } else if (exportFormat === 'CSV' || exportFormat === 'XLSX') {
      const csvHeader = "Branch Name,Volume Share (%),Gross Revenue ($)\n";
      const csvRows = branchSalesData.map(b => `"${b.name}",${b.percent},${b.amount}`).join("\n");
      const csvContent = csvHeader + csvRows;

      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      const ext = exportFormat === 'XLSX' ? 'xlsx' : 'csv';
      link.setAttribute('download', `${reportName}.${ext}`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      addToast(`BI Ledger downloaded (${reportName}.${ext})`, 'success');
    } else if (exportFormat === 'DGI_XML') {
      const xmlContent = `<?xml version="1.0" encoding="UTF-8"?>
<FE_TaxLedger xmlns="http://dgi.mef.gob.pa/fe">
  <Header>
    <RUC>${currentBusiness.taxId}</RUC>
    <DV>${currentBusiness.dv}</DV>
    <Period>${exportRange}</Period>
    <GeneratedDate>${new Date().toISOString()}</GeneratedDate>
  </Header>
  <Totals>
    <GrossSales>340350.00</GrossSales>
    <ITBMS_7>23824.50</ITBMS_7>
    <NetProfitMargin>31.8</NetProfitMargin>
  </Totals>
</FE_TaxLedger>`;
      const blob = new Blob([xmlContent], { type: 'text/xml;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.setAttribute('href', url);
      link.setAttribute('download', `${reportName}.xml`);
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      addToast(`DGI Tax XML Report downloaded (${reportName}.xml)`, 'success');
    }
  };

  return (
    <AppShell>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-5 sm:p-6 rounded-2xl border border-slate-200/80 shadow-xs">
          <div>
            <h1 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight">
              Business Intelligence &amp; Analytics (BI)
            </h1>
            <p className="text-xs sm:text-sm text-slate-500 mt-1">
              Cross-branch consolidated executive reports, product velocity, and AI forecasting.
            </p>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            {/* Filter by Branch */}
            <select
              value={selectedBranchFilter}
              onChange={e => setSelectedBranchFilter(e.target.value)}
              className="text-xs font-semibold bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 outline-none text-slate-700"
            >
              <option value="all">All 4 Branches Consolidated</option>
              {branches.map(b => (
                <option key={b.id} value={b.id}>{b.name.split(' (')[0]}</option>
              ))}
            </select>

            {/* Time range */}
            <div className="bg-slate-100 p-1 rounded-xl flex items-center text-xs font-medium text-slate-600">
              <button
                onClick={() => setSelectedRange('30d')}
                className={`px-3 py-1 rounded-lg transition-all ${
                  selectedRange === '30d' ? 'bg-white text-slate-900 font-bold shadow-2xs' : 'text-slate-600'
                }`}
              >
                30D
              </button>
              <button
                onClick={() => setSelectedRange('90d')}
                className={`px-3 py-1 rounded-lg transition-all ${
                  selectedRange === '90d' ? 'bg-white text-slate-900 font-bold shadow-2xs' : 'text-slate-600'
                }`}
              >
                Q3
              </button>
              <button
                onClick={() => setSelectedRange('ytd')}
                className={`px-3 py-1 rounded-lg transition-all ${
                  selectedRange === 'ytd' ? 'bg-white text-slate-900 font-bold shadow-2xs' : 'text-slate-600'
                }`}
              >
                YTD
              </button>
            </div>

            <button
              onClick={() => setIsExportModalOpen(true)}
              className="flex items-center gap-1.5 px-3 py-2 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold shadow-xs transition-colors"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export BI Report</span>
            </button>
          </div>
        </div>

        {/* AI Insight Box */}
        <div className="p-4 bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-200/80 rounded-2xl flex items-center justify-between text-xs text-blue-900">
          <div className="flex items-center gap-2.5">
            <Sparkles className="w-5 h-5 text-blue-600 shrink-0" />
            <div>
              <p className="font-bold">AI Diagnostic Summary:</p>
              <p className="text-slate-700 leading-relaxed mt-0.5">
                Gross margin is highest in Wearables &amp; Audio (44.2%), while Colon Free Zone provides 39% of total turnover through B2B wholesale. Customer repurchase rate improved by +8.4% since WhatsApp automated order tracking was deployed.
              </p>
            </div>
          </div>
        </div>

        {/* KPIs */}
        <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-4">
          <StatCard
            title="Consolidated Gross Sales"
            value="$340,350"
            change="18.4%"
            isPositive={true}
            subtitle="Trailing 30-day period"
            icon={<CreditCard className="w-5 h-5" />}
          />
          <StatCard
            title="Net Profit Margin"
            value="31.8%"
            change="2.1%"
            isPositive={true}
            subtitle="After COGS and freight"
            icon={<TrendingUp className="w-5 h-5" />}
            iconBg="bg-emerald-50 text-emerald-600"
          />
          <StatCard
            title="Fiscal ITBMS (7%) Collected"
            value="$23,824.50"
            change="12.3%"
            isPositive={true}
            subtitle="DGI Panama e-Factura valid"
            icon={<Receipt className="w-5 h-5 text-indigo-600" />}
            iconBg="bg-indigo-50 text-indigo-600"
          />
          <StatCard
            title="Inventory Turnover"
            value="4.6x"
            subtitle="Annualized velocity"
            icon={<Package className="w-5 h-5" />}
            iconBg="bg-amber-50 text-amber-600"
          />
        </div>

        {/* Financial Flow: Gross vs Tax vs Discounts Breakdown */}
        <div className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-3 border-b border-slate-100">
            <div>
              <h3 className="text-sm font-bold text-slate-900">Revenue Composition &amp; Fiscal Breakdown</h3>
              <p className="text-xs text-slate-500">Gross Sales vs. Promotional Discounts vs. Collected ITBMS Taxes</p>
            </div>
            <div className="flex flex-wrap items-center gap-2 sm:gap-3 text-xs">
              <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded bg-blue-600 inline-block" /> Net Sales ($316,525.50)</span>
              <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded bg-emerald-500 inline-block" /> ITBMS Tax ($23,824.50)</span>
              <span className="flex items-center gap-1.5"><span className="w-3 h-3 rounded bg-rose-400 inline-block" /> Discounts ($14,200.00)</span>
            </div>
          </div>

          <div className="space-y-3">
            <div className="w-full bg-slate-100 h-6 rounded-xl overflow-hidden flex">
              <div style={{ width: '85%' }} className="bg-blue-600 h-full flex items-center justify-center text-[10px] font-bold text-white">
                85% Net
              </div>
              <div style={{ width: '10%' }} className="bg-emerald-500 h-full flex items-center justify-center text-[10px] font-bold text-white">
                7% ITBMS
              </div>
              <div style={{ width: '5%' }} className="bg-rose-400 h-full flex items-center justify-center text-[10px] font-bold text-white">
                Disc
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-2 text-center text-xs">
              <div className="p-3 bg-slate-50 rounded-xl">
                <span className="text-slate-500 block">Gross Volume</span>
                <span className="font-bold text-slate-900 text-sm">$340,350.00</span>
              </div>
              <div className="p-3 bg-emerald-50/60 rounded-xl">
                <span className="text-emerald-700 block font-medium">Panama ITBMS 7%</span>
                <span className="font-bold text-emerald-800 text-sm">+$23,824.50</span>
              </div>
              <div className="p-3 bg-rose-50/60 rounded-xl">
                <span className="text-rose-700 block font-medium">Promos &amp; Coupons</span>
                <span className="font-bold text-rose-800 text-sm">-$14,200.00</span>
              </div>
            </div>
          </div>
        </div>

        {/* Charts Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Branch Revenue Breakdown */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-xs space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="text-sm font-bold text-slate-900">Branch Performance Comparison</h3>
              <span className="text-xs text-slate-500">4 Active Locations</span>
            </div>

            <div className="space-y-4">
              {branchSalesData.map(b => (
                <div key={b.name} className="space-y-1.5 text-xs">
                  <div className="flex justify-between">
                    <span className="font-semibold text-slate-800">{b.name}</span>
                    <span className="font-bold text-slate-900">${b.amount.toLocaleString()} ({b.percent}%)</span>
                  </div>
                  <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden">
                    <div
                      style={{ width: `${b.percent}%` }}
                      className="bg-blue-600 h-full rounded-full transition-all duration-500"
                    ></div>
                  </div>
                </div>
              ))}
            </div>

            <div className="pt-2 text-[11px] text-slate-400">
              * Includes physical POS terminal receipts, warehouse dispatches, and branch click-and-collect orders.
            </div>
          </div>

          {/* Top Products Velocity */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-xs space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <h3 className="text-sm font-bold text-slate-900">Top Velocity Products (30 Days)</h3>
              <span className="text-xs text-emerald-600 font-bold bg-emerald-50 px-2 py-0.5 rounded-full">
                High Margin
              </span>
            </div>

            <div className="divide-y divide-slate-100 text-xs">
              {mockProducts.slice(0, 4).map(prod => (
                <div key={prod.id} className="py-2.5 flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img src={prod.images[0]} alt={prod.name} className="w-8 h-8 rounded-lg object-cover border border-slate-200" />
                    <div>
                      <p className="font-bold text-slate-900">{prod.name}</p>
                      <p className="text-[10px] text-slate-400 font-mono">SKU: {prod.sku}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <span className="font-bold text-slate-900">${prod.price.toFixed(2)}</span>
                    <p className="text-[10px] text-emerald-600 font-semibold">{prod.stock} units in stock</p>
                  </div>
                </div>
              ))}
            </div>

            <div className="pt-2 text-right">
              <span
                onClick={() => setIsExportModalOpen(true)}
                className="text-xs text-blue-600 font-bold hover:underline cursor-pointer"
              >
                Export SKU Velocity CSV →
              </span>
            </div>
          </div>
        </div>

        {/* BI Report Export Modal */}
        <Modal
          isOpen={isExportModalOpen}
          onClose={() => setIsExportModalOpen(false)}
          title="Export Business Intelligence &amp; Tax Report"
        >
          <div className="space-y-4 text-xs">
            <p className="text-slate-600">
              Configure parameters to generate consolidated financial statements, product velocity reports, and Panama DGI ITBMS tax reports.
            </p>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">Report Format</label>
              <Select
                value={exportFormat}
                onChange={e => setExportFormat(e.target.value)}
                options={[
                  { value: 'PDF', label: 'Executive Presentation (PDF with Charts)' },
                  { value: 'XLSX', label: 'Financial Spreadsheet (Excel .xlsx)' },
                  { value: 'CSV', label: 'Raw Ledger Data (CSV)' },
                  { value: 'DGI_XML', label: 'Panama DGI e-Factura Tax Ledger (XML)' }
                ]}
              />
            </div>

            <div>
              <label className="block font-semibold text-slate-700 mb-1">Time Horizon</label>
              <Select
                value={exportRange}
                onChange={e => setExportRange(e.target.value)}
                options={[
                  { value: '30d', label: 'Current Month (30 Days)' },
                  { value: '90d', label: 'Current Quarter (Q3 2026)' },
                  { value: 'ytd', label: 'Year to Date (YTD 2026)' },
                  { value: 'fiscal_2025', label: 'Previous Fiscal Year 2025' }
                ]}
              />
            </div>

            <div className="space-y-2 p-3 bg-slate-50 border border-slate-200 rounded-xl">
              <span className="font-semibold text-slate-700 block">Report Inclusions:</span>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" defaultChecked className="rounded border-slate-300 text-indigo-600" />
                <span>Panama DGI ITBMS (7%, 10%, 15%) Tax Reconciliation</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" defaultChecked className="rounded border-slate-300 text-indigo-600" />
                <span>Inter-branch inventory transfer logs &amp; COGS</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" defaultChecked className="rounded border-slate-300 text-indigo-600" />
                <span>Affiliate commissions &amp; marketing attribution (ROAS)</span>
              </label>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <Button variant="outline" onClick={() => setIsExportModalOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleExecuteExport}>
                Generate &amp; Download {exportFormat}
              </Button>
            </div>
          </div>
        </Modal>
      </div>
    </AppShell>
  );
}
